version: "3.3"

services:
  backend:
    build: 
      context: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=craftech

    stdin_open: true
    
    tty: true
    
    command: python3 manage.py runserver 0.0.0.0:8000

  frontend:
    
    build: ./frontend

    volumes: 

      - ./frontend:/app

      - /app/node_modules

    ports:
    
      - "3000:3000"

    environment:

      - NODE_ENV=development

    depends_on:

      - backend

    command: npm start
   
