on: push
name: deploy
jobs:
  deploy:
    name: ci and cd
    runs-on: ubuntu-latest
    steps:
      - uses: shashank0202/docker-build-push-gcr-update-gke-deployment-action@v1.4
        with:
          service_account: ${{ secrets.GCLOUD_AUTH }} 
          zone: 'us-central1-c'
          project_id: 'careful-ensign-302119'
          registry: 'gcr.io'
          image_name: 'mi-nginx'
          cluster: 'cluster1'
          namespace: 'default'
          deployment: 'nginx-2'
          container: 'mi-nginx'
